### ISSUE TITLE
Remove deploy of develop branch from CircleCI

### ISSUE THREAD

**Issue by jamesbondev** [Jbond312/Food-Commerce#15]
Due to the source code previously being used to deploy to Linode whenever a push to 'develop' was made. This integration hasn't currently been fully configured and therefore should temporarily be removed.

The short solution is to just remove the deploy step itself from the circle ci config file.

**Comment by hssahan** [comment]
Do we want a server again or nah?

**Comment by jamesbondev** [comment]
Eventually yeh, don't need one now. Might be worth looking to see if anyone allows for free hosting for open source apps, doubtful but worth a look.

**Comment by hssahan** [comment]
I don't know if this sounds silly, but I do have raspberry pi sitting around which is always on and doesnt do anything.

**Comment by jamesbondev** [comment]
Up to you really, you'll end up having to expose your IP and allow access via specific ports. Probably not worth it.
